### ISSUE TITLE
java.lang.NumberFormatException: For input string: "262520049635900"

### ISSUE THREAD

**Issue by qianqian78** [redkale/redkale#10]
Exception in thread "Redkale-Application-Main-Thread" java.lang.NumberFormatException: For input string: "262520049635900"
	at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.base/java.lang.Integer.parseInt(Integer.java:652)
	at java.base/java.lang.Integer.parseInt(Integer.java:770)
	at org.redkale.boot.Application.<init>(Application.java:276)
	at org.redkale.boot.Application.create(Application.java:1138)
	at org.redkale.boot.Application.main(Application.java:1195)

**Comment by redkale** [comment]
已修复
